import { Car } from './car';

//* create mock data list
export const CARLIST: Car[] = [
    {   id: 1, 
        type: 'Cars', 
        year: 2014, 
        make: 'Mazda', 
        model: '3', 
        transmissionType: 'Automatic', 
        vehicleStatus: 'Used', 
        price: 15000,
        fuelType: 'Gasoline',
        kilometres: 21000,
        hasCarProof: true,
        datePosted: new Date('11/06/2018')
    },
    {   id: 2, 
        type: 'SUVs', 
        year: 2018, 
        make: 'Acura', 
        model: 'MDX', 
        transmissionType: 'Automatic', 
        vehicleStatus: 'New', 
        price: 45000,
        fuelType: 'Gasoline',
        kilometres: 0,
        hasCarProof: false,
        datePosted: new Date('10/06/2018')
    },
    {   id: 3, 
        type: 'Vans', 
        year: 2016, 
        make: 'Honda', 
        model: 'Odyssey', 
        transmissionType: 'Automatic', 
        vehicleStatus: 'Used', 
        price: 25000,
        fuelType: 'Gasoline',
        kilometres: 35000,
        hasCarProof: true,
        datePosted: new Date('05/05/2018')
    },
    {   id: 4, 
        type: 'Cars', 
        year: 2018, 
        make: 'Honda', 
        model: 'Accord', 
        transmissionType: 'Automatic', 
        vehicleStatus: 'New', 
        price: 30000,
        fuelType: 'Gasoline',
        kilometres: 0,
        hasCarProof: false,
        datePosted: new Date('01/01/2018')
    },
];
